config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'users#choose'

  #For channels
  get 'create_channel' => 'channels#new'
  get 'join_channel' => 'sessions#joining_a_channel' #shows that page I think
  post 'join_channel' => 'sessions#new_order'        #happens upon clicking the submit button in the joining_a_channel page
  get 'current_channel' => 'channels#show'
  delete 'sessions' => 'sessions#quit'
  get 'exit' => 'users#choose'
  get 'all_channels' => "channels#display"
  get 'channel' => 'channels#toggle_status'
  
  get 'add_item' => 'orders#new'
  post 'orders' => 'orders#create'
  get 'all_orders' => 'orders#show'
  delete 'orders' => 'orders#destroy'
  get "collate" => 'orders#collate'
  
  get 'bill' => 'channels#bill'
  get 'send_bill' => 'users#bill'
  
  #For user log in log out
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#new'
  get 'join_or_create' => 'users#choose'
  get 'about' => 'users#about'

  #For user profile
  get 'settings' => 'users#edit'
  
  # Admin Pages
  get 'admin' => 'users#admin'
  get 'admin_channels' => 'channels#admin_channels'
  delete 'channels' => 'channels#destroy'
  get 'admin_users' => 'users#admin_users'
  delete 'users' => 'users#destroy'
  
  resources :orders
  resources :users
  resources :channels
  resources :menu_items, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :orders
  before_save :update_subtotal
  
  belongs_to :user
  
  validates :cname, presence: true, uniqueness: {case_sensitive: true}, length: {maximum: 20}
  validates :menu, presence: true
  validates :delivery, presence: true
  
  def subtotal
    orders.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
private

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :logged_in_user  
  before_action :admin_user, only: :destroy

  def show
    if !current_channel.nil? && current_channel.channel_status == "Open"
      @orders = current_channel.orders
      @channel = current_channel
    else 
      if current_channel.nil?
        flash[:danger] = "You are not in any channel. Please create or join a channel."
        redirect_to join_or_create_path
      else 
        redirect_to bill_path
      end
    end
  end

  def display
    @channel_owner = current_user.channels
    @user = current_user
  end 

  def new
    @channel_owner = Channel.new
  end

  def admin_channels
    @channels = Channel.all
  end

  def create 
    @channel_owner = current_user.channels.new(channel_params)
    @channel_owner.channel_status = "Open"

    if @channel_owner.save    
      join_channel(@channel_owner)
      flash[:success] = "Success!"
      @channel = current_channel
      redirect_to current_channel_path
    else 
      flash.now[:danger] 
      render 'new'
    end 
  end 

  def toggle_status   
    @channel = current_channel
    if @channel.channel_status == "Closed"
      @channel.update_attribute(:channel_status, "Open")
      flash[:success] = "This channel is now open."
      redirect_to current_channel_path
    else
      @channel.update_attribute(:channel_status, "Closed")
      redirect_to collate_path
    end
  end

  def bill
    if current_channel.nil?
      flash[:danger] = "Please create or join a channel."
      redirect_to join_or_create_path
    else
      @channel = current_channel
      @bills ||= current_channel.orders.group(:user_id)
      @orders = @channel.orders
    end
  end

  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
    @channels = Channel.all
    flash[:success] = "Channel deleted."
    redirect_to admin_channels_path
  end

  private 
  def channel_params
    params.require(:channel).permit(:cname, :menu, :channel_status, :delivery, :created_at)
  end 
end 

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/admin_channels.html.erb
<% @title="tamchiak | All Channels (Admin)" %>

<body>
  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_admin' %>

  <!-- CONTENT -->
  <div class="container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Channel</th>
          <th>Menu</th>
          <th>Owner</th>
          <th>Channel Status</th>
          <th>Date created</th>
          <th></th>
        </tr>        
      </thead>
      <tbody>
        <% @channels.each do |t| %>
        <p>
          <tr>
            <td><%= t.cname %></td>
            <td><%= t.menu %></td>              
            <td><%= t.added_by %></td>
            <td><%= t.channel_status %></td>
            <td><%= t.created_at.strftime("%d %b %Y") %></td>              
            <td><%= form_for(:session, url: join_channel_path) do |f| %>
              <%= f.hidden_field :cname, :value => t.cname %>
              <%= f.submit  "Join", {class: "btn btn-primary btn-sm"} %>
              <% end %></td>

          </tr>
        </p>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/channels/all_channels.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>All Channels</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="bootstrap.min.css">
  </head>

  <body>
    <!-- NAVIGATION BAR -->
    <%= render 'layouts/header_channels' %>

    <!-- CONTENT -->

    <button type="button"  class: "btn btn-primary" data-no-turbolink="true"><%= link_to "Home", join_or_create_path %></button>
    <% if current_channel.user_id == current_user.id %>

    <div class="container">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Channel Name</th>
            <th>Channel Owner</th>
            <th>Action</th>
          </tr>        
        </thead>
        <tbody>
          <% @channels.find_each do |t| %>
          <p>
            <tr>
              <td><%= t.cname %></td>
              <td><%= t.email %></td>
              <td><%= link_to 'Delete', t, :method => :destroy %></td>
            </tr>
          </p>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/channels/bill.html.erb
<% @title="tamchiak | Bill for #{@channel.cname}" %>

<body>
  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_current' %>

  <!-- CONTENT -->
  <% if @channel.channel_status == "Closed" %>
  <div class="alert alert-danger" role="alert">This channel is closed. You can still view the collated order and bill pages.</div>
  <% else %>
  <div class="alert alert-info" role="alert">To send out bill reminders to your friends who have ordered in this channel, please first close the channel.</div>  
  <% end %>

  <div class="container">
    <div class="row">
      <h1>
        <strong><%= current_channel.cname %></strong> <small>Bill</small>

        <div class="pull-right">
          <%= link_to "Collated Order", collate_path, {class: "btn btn-default", data: { no_turbolink: true }} %>
          <% if @channel.channel_status == "Closed" && (current_channel.user_id == current_user.id || current_user.is_admin) %>
          <%= link_to "Send Bill", send_bill_path, {class: "btn btn-primary", data: { no_turbolink: true }} %>
          <% end %>
        </div>
      </h1>
    </div>
    <p></p>

    <% if @orders.size == 0 %>
    <div class="well">
      There are no bills payable.
    </div>
    <% else %>

    <% @bills.each do |t| %>

    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= t.user.name %></strong> ordered <abbr title="attribute"><%= number_to_currency(@bills.sum(:total_price)[t.user_id] + (@channel.delivery / @orders.count(t.user_id, :distinct => true))) %></abbr> worth of food</h3>  
      </div>

      <div class="panel-body">
        <div class="table-responsive">

          <table class="table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Item Code</th>
                <th>Name</th>
                <th>Remarks</th>
                <th>Quantity</th>
                <th>Total Price</th>
              </tr>
            </thead>
            <tbody> 
              <% @orders.where(user_id: t.user_id).find_each do |s| %>

              <p>
                <tr>
                  <td><%= s.cat %></td>
                  <td><%= s.item_code %></td>
                  <td class="col-md-6"><%= s.meal %></td>
                  <td><%= s.subcat %></td>
                  <td><%= s.quantity %></td>
                  <td><%= number_to_currency(s.total_price) %></td>
                </tr>
              </p>
              <% end %>
            </tbody>

          </table>
        </div>
      </div>
    </div>

    <% end %>
    <% end %>

    <small>NOTE: Bills payable include delivery cost.</small>
    <p></p>

  </div>
</body>

app/views/channels/display.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% @title="tamchiak | Your channels" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <!-- NAVIGATION BAR -->
    <%= render 'layouts/header_channels' %>

    <!-- CONTENT -->

    <div class="container">

      <h1>
        Channels created by <strong><%= @user.name %></strong>
      </h1>
      <p></p>
      <% if @channel_owner.size == 0 %>
      <div class="well">
        You have no channels. Would you like to <%= link_to "create a channel", create_channel_path %>?
      </div>
      <% else %>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Channel Name</th>
              <th>Menu</th>
              <th>Channel Status</th>
              <th>Date created</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @channel_owner.each do |t| %>
            <p>
              <tr>
                <td class="col-md-6"><%= t.cname %></td>
                <td><%= t.menu %></td>
                <td><%= t.channel_status %></td>
                <td><%= t.created_at.strftime("%d %b %Y") %></td>
                <td><%= form_for(:session, url: join_channel_path) do |f| %>
                  <%= f.hidden_field :cname, :value => t.cname %>
                  <%= f.submit  "Enter", {class: "btn btn-primary btn-sm"} %>
                  <% end %></td>

              </tr>
            </p>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </div>
  </body>

app/views/channels/show.html.erb
<% @title="tamchiak | Channel #{@channel.cname}" %>

<body>
  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_current' %>

  <!-- CONTENT -->  
  <div class="container">
    <div class="row">
      <h1>
        <strong><%= @channel.cname %></strong> <small>Channel</small>
        <div class="pull-right">
          <%= link_to "Add item", add_item_path, {class: "btn btn-default", data: { no_turbolink: true }} %>
          <%= link_to "Collate Orders", collate_path, {class: "btn btn-primary", data: { no_turbolink: true }}  %>
        </div>
      </h1>
    </div>

    <% if @orders.size == 0 %>
    <div class="well">
      You have no orders in your channel.
    </div>

    <% else %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Item code</th>
            <th>Name</th>
            <th>Remarks</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Added by</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |t| %>
          <p>
            <tr>
              <td><%= t.item_code %></td>
              <td class="col-md-5"><%= t.meal %></td>
              <td><%= t.subcat %></td>
              <td><%= number_to_currency(t.unit_price) %></td>
              <td><%= t.quantity %></td>
              <td><%= t.user.name %></td>              
              <td><%= link_to 'Delete', t, :method => :delete %></td>
            </tr>
          </p>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>

  <div>
    <div class="pull-right" align="right">
      <h4><small><%= render 'layouts/channel_text' %> | Delivery: <%= number_to_currency(@channel.delivery) %></small></h4>
      <h3>Total: <%= number_to_currency(@orders.sum(:total_price) + @channel.delivery) %></h3>
    </div>
  </div>

</body>