config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'users#choose'

  #For channels
  get 'create_channel' => 'channels#new'
  get 'join_channel' => 'sessions#joining_a_channel' #shows that page I think
  post 'join_channel' => 'sessions#new_order'        #happens upon clicking the submit button in the joining_a_channel page
  get 'current_channel' => 'channels#show'
  delete 'sessions' => 'sessions#quit'
  get 'exit' => 'users#choose'
  get 'all_channels' => "channels#display"
  get 'channel' => 'channels#toggle_status'
  
  get 'add_item' => 'orders#new'
  post 'orders' => 'orders#create'
  get 'all_orders' => 'orders#show'
  delete 'orders' => 'orders#destroy'
  get "collate" => 'orders#collate'
  
  get 'bill' => 'channels#bill'
  get 'send_bill' => 'users#bill'
  
  #For user log in log out
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#new'
  get 'join_or_create' => 'users#choose'
  get 'about' => 'users#about'

  #For user profile
  get 'settings' => 'users#edit'
  
  # Admin Pages
  get 'admin' => 'users#admin'
  get 'admin_channels' => 'channels#admin_channels'
  delete 'channels' => 'channels#destroy'
  get 'admin_users' => 'users#admin_users'
  delete 'users' => 'users#destroy'
  
  resources :orders
  resources :users
  resources :channels
  resources :menu_items, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :channels, dependent: :destroy
  has_many :orders, dependent: :destroy

  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50},  uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end  
    
  # Sends billing email.
  def send_billing_email(current_channel)
    UserMailer.send_bill(self, current_channel).deliver_now
  end

  private 
  #Converts emails to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :logged_in_user, only: [:edit, :update, :choose, :destroy]
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
  end 

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to login_path
    else 
      render 'new'
    end 
  end 

  def destroy
    @user = User.find(params[:id])
    if (@user == current_user)
      flash[:danger] = "You cannot delete your own account!"
      redirect_to admin_users_path
    else
      @user.destroy
      @users = User.all
      flash[:success] = "User deleted."
      redirect_to admin_users_path
    end
  end

  def admin_users
    @users = User.all
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to join_or_create_path
    else
      render 'edit'
    end
  end

  def bill 
    @relevant_orders = Order.where(channel_id: current_channel.id)
    @relevant_orders.each do |t|
      @customer = User.find(t.user_id)
      @customer.send_billing_email(current_channel)
    end
    flash[:info] = "The bills have been sent!"
    redirect_to bill_path
  end 

  # Sends password reset email.
  def send_billing_email
    UserMailer.send_bill(self, current_channel).deliver_now
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<% @title="tamchiak | About" %>

<body>

  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_about' %>

  <!-- CONTENT -->
  <div class="container well">
    <div class="center" >
      <div class="row">
        
        <h1 align="center">About tamchiak</h1>
<p align="left">
  Hello <strong><%= current_user.name %></strong>, thank you for using tamchiak! Tamchiak, or greedy in hokkien, aims to help you collate meal orders in a hassle free manner. <br/>
        <br/>

  To collate orders, simply <%= link_to "create a channel", create_channel_path %>, and pm your channel name to your friends. When all the orders are in, close the channel and send the bill (inclusive of delivery charge) to your friends! To place an order with your friends, simply <%= link_to "join a channel", join_channel_path %>, place your orders and wait for the food (and bill) to come! <br/>
        <br/>
        We are still working on other menu options and integrating online ordering to this app so do check back soon! Feel free to drop us an email at tamchiakorbital@gmail.com for any feedback or bugs. <br/>
        <br/>
        Love, Szeying and Annabel from <b>tamchiak</b> ^_^
        </p>

    </div>
  </div>
  </div>
</div>
</body>

app/views/users/admin.html.erb
<% @title="tamchiak | Admin" %>

<body>

  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_admin' %>

  <!-- CONTENT -->
  <div class="container well">
    <div class="center" align="center">
      <div class="row">
        <p>
        <h1>Hello, admin <strong><%= current_user.name %></strong>!</h1>
        </p>   
      <p>
        <%= link_to "All Channels", admin_channels_path, {class: "btn btn-primary btn-lg", data: { no_turbolink: true }} %>
        <%= link_to "All Users", admin_users_path, {class: "btn btn-default btn-lg", data: { no_turbolink: true }} %> 
      </p>

    </div>
  </div>
  </div>
</div>
</body>

app/views/users/admin_users.html.erb
<% @title="tamchiak | All users" %>

<body>
  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_admin' %>

  <!-- CONTENT -->
  <div class="container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Action</th>
        </tr>        
      </thead>
      <tbody>
        <% @users.each do |t| %>
        <p>
          <tr>
            <td><%= t.name %></td>
            <td><%= t.email %></td>
            <td><%= link_to 'Delete', t, :method => :delete %></td>
          </tr>
        </p>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/users/choose.html.erb
<% @title="tamchiak | Home" %>

<body>
  <div class="container">
    <!-- NAVIGATION BAR -->
    <%= render 'layouts/header' %>

    <!-- CONTENT -->
    <div class="container well">
      <div class="center" align="center">
        <div class="row">
          <p>
          <h1>Welcome, <strong><%= current_user.name %></strong>!</h1>
          <h2><small>What would you like to do?</small></h2>
          </p>   
        <p>
          <%= link_to "Create a channel", create_channel_path, {class: "btn btn-primary btn-lg", data: { no_turbolink: true }} %>
          <%= link_to "Join a channel", join_channel_path, {class: "btn btn-default btn-lg", data: { no_turbolink: true }} %> 
        </p>

      </div>
    </div>
  </div>
  </div>
</div>
</body>

app/views/users/edit.html.erb
<% @title="tamchiak | Settings" %>

<body>
  <!-- NAVIGATION BAR -->
  <%= render 'layouts/header_users' %>

  <!-- CONTENT -->
  <div class="container">
    <div class="col-md-10 col-md-offset-1">

      <h1>Update your profile</h1>

      <div class="panel panel-default">
        <div class="panel-body">

          <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :name %>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <%= f.label :email %>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <%= f.label :password %>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <%= f.label :password_confirmation, "Confirmation" %>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <p></p>
          <%= f.submit "Save changes", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/new.html.erb
<% @title="tamchiak | Sign up" %>

<div class="row">
  <div class = "col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :username %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- NAVIGATION BAR -->
<%= render 'layouts/header' %>

<!-- CONTENT -->


<% @title="tamchiak | Profile" %>

<%= @user.name %>
<%= @user.email %>
<%= link_to "Log out", logout_path %>