config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'users#choose'

  #For channels
  get 'create_channel' => 'channels#new'
  get 'join_channel' => 'sessions#joining_a_channel' #shows that page I think
  post 'join_channel' => 'sessions#new_order'        #happens upon clicking the submit button in the joining_a_channel page
  get 'current_channel' => 'channels#show'
  delete 'sessions' => 'sessions#quit'
  get 'exit' => 'users#choose'
  get 'all_channels' => "channels#display"
  get 'channel' => 'channels#toggle_status'
  
  get 'add_item' => 'orders#new'
  post 'orders' => 'orders#create'
  get 'all_orders' => 'orders#show'
  delete 'orders' => 'orders#destroy'
  get "collate" => 'orders#collate'
  
  get 'bill' => 'channels#bill'
  get 'send_bill' => 'users#bill'
  
  #For user log in log out
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#new'
  get 'join_or_create' => 'users#choose'
  get 'about' => 'users#about'

  #For user profile
  get 'settings' => 'users#edit'
  
  # Admin Pages
  get 'admin' => 'users#admin'
  get 'admin_channels' => 'channels#admin_channels'
  delete 'channels' => 'channels#destroy'
  get 'admin_users' => 'users#admin_users'
  delete 'users' => 'users#destroy'
  
  resources :orders
  resources :users
  resources :channels
  resources :menu_items, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_channel_text.html.erb
<%= "Subtotal: #{number_to_currency(current_channel.subtotal)}" %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", about_path, {class: "navbar-brand"} %>
        
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">

          <li class="active"><%= link_to "Home",   join_or_create_path %></li>
          <li><%= link_to "Current Channel",   current_channel_path %></li>
          <li><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_about.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header active">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", about_path, {class: "navbar-brand"} %>
        
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">

          <li><%= link_to "Home",   join_or_create_path %></li>
          <li><%= link_to "Current Channel",   current_channel_path %></li>
          <li><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_admin.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", join_or_create_path, {class: "navbar-brand"} %>

      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-left">

          <li><%= link_to "Home",   join_or_create_path %></li>
          <li><%= link_to "Current Channel",   current_channel_path %></li>
          <li><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li class="active"><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_channels.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", about_path, {class: "navbar-brand"} %>
        
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">

          <li><%= link_to "Home",   join_or_create_path %></li>
          <li><%= link_to "Current Channel",   current_channel_path %></li>
          <li class="active"><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_current.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", about_path, {class: "navbar-brand"} %>
        
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">

          <li><%= link_to "Home",   join_or_create_path %></li>
          <li class="active"><%= link_to "Current Channel",   current_channel_path %></li>
          <li><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header_users.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to "tamchiak", about_path, {class: "navbar-brand"} %>
        
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">

          <li><%= link_to "Home",   join_or_create_path %></li>
          <li><%= link_to "Current Channel",   current_channel_path %></li>
          <li><%= link_to "Your Channels",   all_channels_path %></li>
          <% if current_user.is_admin? %>
          <li><%= link_to "Admin", admin_path %></li>
          <% end %>
          <li class="active"><%= link_to "Settings",   settings_path %></li>
        </ul>

        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %>.   <%= link_to "Sign out", logout_path %></p>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "jquery", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "bootsnip", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "bootstrap.min.js", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "javascripts", 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "custom" %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
    <div class="container" style="margin-top: 10px">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      </body>
    </html>